server:
  port: 8002

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sotilon/selconfig112022
          clone-on-start: true
          skipSslValidation: true


eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8001/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

