POST http://localhost:8003/api/v1/account/save
Content-Type:application/json
  {
    "accountNumber": "ACC54321",
    "minimumBalance": 200.00,
    "currentBalance": 6000.00,
    "interestRate": 2.50
  }


DEL http://localhost:8003/api/v1/account/delete
Content-Type:application/json
  {
    "accountNumber": "ACC54321",
    "minimumBalance": 200.00,
    "currentBalance": 6000.00,
    "interestRate": 2.50
  }
