# get all customers
GET http://localhost:8000/api/v1/customer/list

# get by customer id
GET http://localhost:8000/api/v1/customer/1

#find all accounts from api-account using feign
GET http://localhost:8000/api/v1/customer/accounts

#find by account id  from api-account using feign
GET http://localhost:8000/api/v1/customer/account/3

